### ISSUE TITLE
Some Modules not found When run in Windows.

### ISSUE THREAD

**Issue by Talhamehar007** [4n4nk3/TinkererShell#5]
It works perfectly in Linux, But when I try to run it in Windows, there are some modules that are missing and I can't even install them using pip. Like _winreg, pyHook, etc not found Error. I have tried installing these modules but all in vain.

I removed the keyLogger function and now it's working but still facing some issues.

**Comment by 4n4nk3** [comment]
Can you please copy and paste here the exact error message and the commands you used?
Meanwhile, you can try to use `pip install pywin32 pyHook`.
