### ISSUE TITLE
Error while downloading files.

### ISSUE THREAD

**Issue by Talhamehar007** [4n4nk3/TinkererShell#6]
Whenever i try to take a screenshot or webcampic or download a file, it says <Name of the file > path  not found.

**Comment by 4n4nk3** [comment]
Can you please copy and paste here the exact error message and the commands you used?

**Comment by Talhamehar007** [comment]
Whenever i run this command **"SHscreenshot"** or **"SHdownload <filename>"**. It Says that file not found.

Here's the result of SHscreenshot command:

`(SHCmd) SHscreenshot`

`[Errno 2] No such file or directory: 'screenshot-127.0.0.1-windows-desktop\\talha-0.png'`

**Comment by 4n4nk3** [comment]
Thank you.
Should have fixed the problem with the following pull request: #7.
Please update your local copy of the repository and let me know if it does fix it for you.
